

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;



CREATE TABLE public.cities (
    id integer NOT NULL,
    name character varying(75) NOT NULL,
    is_active boolean DEFAULT true,
    is_deleted boolean DEFAULT false,
    created_at date DEFAULT CURRENT_DATE
);


ALTER TABLE public.cities OWNER TO postgres;



ALTER TABLE public.cities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




CREATE TABLE public.cv_cover_letters (
    id integer NOT NULL,
    content character varying NOT NULL,
    created_at date DEFAULT CURRENT_DATE,
    is_active boolean DEFAULT true,
    is_deleted boolean DEFAULT false,
    jobHunter_id integer NOT NULL
);


ALTER TABLE public.cv_cover_letters OWNER TO postgres;



ALTER TABLE public.cv_cover_letters ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cover_letters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.cv_experiences (
    id integer NOT NULL,
    working_place character varying(200) NOT NULL,
    "position" character varying(200) NOT NULL,
    start_at date NOT NULL,
    end_at date,
    created_at date DEFAULT CURRENT_DATE,
    is_active boolean DEFAULT true,
    is_deleted boolean DEFAULT false,
    jobHunter_id integer NOT NULL
);


ALTER TABLE public.cv_experiences OWNER TO postgres;



CREATE TABLE public.cv_foreign_languages (
    id integer NOT NULL,
    language character varying NOT NULL,
    level integer NOT NULL,
    created_at date DEFAULT CURRENT_DATE,
    is_active boolean DEFAULT true,
    is_deleted boolean DEFAULT false,
    jobHunter_id integer NOT NULL
);


ALTER TABLE public.cv_foreign_languages OWNER TO postgres;



CREATE TABLE public.cv_images (
    id integer NOT NULL,
    url character varying NOT NULL,
    is_active boolean DEFAULT true,
    is_deleted boolean DEFAULT false,
    created_at date DEFAULT CURRENT_DATE,
    jobHunter_id integer NOT NULL,
    jobHunter_user_id integer
);


ALTER TABLE public.cv_images OWNER TO postgres;


ALTER TABLE public.cv_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cv_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




CREATE TABLE public.cv_links (
    id integer NOT NULL,
    url character varying NOT NULL,
    created_at date DEFAULT CURRENT_DATE,
    is_active boolean DEFAULT true,
    is_deleted boolean DEFAULT false,
    name character varying NOT NULL,
    jobHunter_id integer NOT NULL
);


ALTER TABLE public.cv_links OWNER TO postgres;



ALTER TABLE public.cv_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cv_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




CREATE TABLE public.cv_programming_language (
    id integer NOT NULL,
    pLanguage_name character varying(100) NOT NULL,
    created_at date DEFAULT CURRENT_DATE,
    is_active boolean DEFAULT true,
    is_deleted boolean DEFAULT false,
    jobHunter_id integer NOT NULL
);


ALTER TABLE public.cv_programming_skills OWNER TO postgres;



CREATE TABLE public.cv_schools (
    id integer NOT NULL,
    name character varying(300) NOT NULL,
    department character varying(200) NOT NULL,
    start_at date NOT NULL,
    end_at date,
    created_at date DEFAULT CURRENT_DATE,
    is_active boolean DEFAULT true,
    is_deleted boolean DEFAULT false,
    jobHunter_id integer NOT NULL
);


ALTER TABLE public.cv_schools OWNER TO postgres;



ALTER TABLE public.cv_schools ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cv_schools_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.staffers (
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL
);


ALTER TABLE public.staffers OWNER TO postgres;



CREATE TABLE public.employers (
    user_id integer NOT NULL,
    website character varying(250) NOT NULL,
    phone_number character varying(30) NOT NULL,
    is_verified boolean NOT NULL,
    company_name character varying(250) NOT NULL
);


ALTER TABLE public.employers OWNER TO postgres;



CREATE TABLE public.authentication_codes (
    id integer NOT NULL,
    user_id integer NOT NULL,
    code character varying(50) NOT NULL,
    is_confirmed boolean NOT NULL,
    created_at date DEFAULT CURRENT_DATE,
    is_active boolean DEFAULT true,
    is_deleted boolean DEFAULT false
);


ALTER TABLE public.authentication_codes OWNER TO postgres;



ALTER TABLE public.authentication_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employers_authentication_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.employers_authentication_staffers(
    id integer NOT NULL,
    employer_id integer NOT NULL,
    staffer_id integer NOT NULL,
    created_at date DEFAULT CURRENT_DATE NOT NULL
);


ALTER TABLE public.employers_authentication_staffers OWNER TO postgres;



ALTER TABLE public.employers_authentication_staffers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employers_authentication_staffers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




ALTER TABLE public.cv_experiences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.experiences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




ALTER TABLE public.cv_foreign_languages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.foreign_languages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE SEQUENCE public.hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.hibernate_sequence OWNER TO postgres;


CREATE TABLE public.job_adverts (
    id integer NOT NULL,
    position_id integer NOT NULL,
    description character varying NOT NULL,
    city_id integer NOT NULL,
    open_position_count integer NOT NULL,
    deadline date NOT NULL,
    is_open boolean,
    created_at date NOT NULL,
    is_active boolean,
    is_deleted boolean,
    employer_id integer NOT NULL,
    published_at date NOT NULL,
    salary_min integer,
    salary_max integer
);


ALTER TABLE public.job_adverts OWNER TO postgres;



ALTER TABLE public.job_adverts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_adverts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




CREATE TABLE public.positions (
    id integer NOT NULL,
    position_name character varying(150) NOT NULL,
    created_date date,
    is_actived boolean,
    is_deleted boolean
);


ALTER TABLE public.positions OWNER TO postgres;



ALTER TABLE public.positions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.positions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




CREATE TABLE public.jobHunters (
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    national_id character varying(11) NOT NULL,
    is_verified boolean DEFAULT false NOT NULL,
    date_of_birth date NOT NULL
);


ALTER TABLE public.jobHunters OWNER TO postgres;



ALTER TABLE public.cv_programming_language ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cv_programming_language_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




CREATE TABLE public.users (
    id integer NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(30) NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean
);


ALTER TABLE public.users OWNER TO postgres;



ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.cv_cover_letters
    ADD CONSTRAINT cover_letters_pkey PRIMARY KEY (id);




ALTER TABLE ONLY public.cv_images
    ADD CONSTRAINT cv_images_pkey PRIMARY KEY (id);




ALTER TABLE ONLY public.cv_links
    ADD CONSTRAINT cv_links_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.cv_schools
    ADD CONSTRAINT cv_schools_pkey PRIMARY KEY (id);




ALTER TABLE ONLY public.staffers
    ADD CONSTRAINT staffers_pkey PRIMARY KEY (user_id);




ALTER TABLE ONLY public.employers
    ADD CONSTRAINT employers_pkey PRIMARY KEY (user_id);




ALTER TABLE ONLY public.authentication_codes
    ADD CONSTRAINT authentication_codes_pkey PRIMARY KEY (id);




ALTER TABLE ONLY public.employers_authentication_staffers
    ADD CONSTRAINT employers_authentication_staffers_pkey PRIMARY KEY (id);




ALTER TABLE ONLY public.cv_experiences
    ADD CONSTRAINT experiences_pkey PRIMARY KEY (id);




ALTER TABLE ONLY public.cv_foreign_languages
    ADD CONSTRAINT foreign_languages_pkey PRIMARY KEY (id);




ALTER TABLE ONLY public.job_adverts
    ADD CONSTRAINT job_adverts_pkey PRIMARY KEY (id);




ALTER TABLE ONLY public.positions
    ADD CONSTRAINT positions_pkey PRIMARY KEY (id);




ALTER TABLE ONLY public.jobHunters
    ADD CONSTRAINT jobHunters_national_id_key UNIQUE (national_id) INCLUDE (national_id);




ALTER TABLE ONLY public.jobHunters
    ADD CONSTRAINT jobHunters_pkey PRIMARY KEY (user_id);




ALTER TABLE ONLY public.cv_programming_language
    ADD CONSTRAINT cv_programming_language_pkey PRIMARY KEY (id);




ALTER TABLE ONLY public.cv_images
    ADD CONSTRAINT uk_oxr4t115vjkx8mtlwi984qxbj UNIQUE (jobHunter_user_id);



ALTER TABLE ONLY public.cv_images
    ADD CONSTRAINT uk_t9k5o9uta40uhd6tvgobc5h9h UNIQUE (jobHunter_id);




ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email) INCLUDE (email);




ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);




ALTER TABLE ONLY public.job_adverts
    ADD CONSTRAINT city_fk_id FOREIGN KEY (city_id) REFERENCES public.cities(id) NOT VALID;




ALTER TABLE ONLY public.employers_authentication_staffers
    ADD CONSTRAINT staffer_id FOREIGN KEY (staffer_id) REFERENCES public.staffers(user_id) NOT VALID;




ALTER TABLE ONLY public.job_adverts
    ADD CONSTRAINT employer_fk_id FOREIGN KEY (employer_id) REFERENCES public.employers(user_id) NOT VALID;




ALTER TABLE ONLY public.employers_authentication_staffers
    ADD CONSTRAINT employer_id FOREIGN KEY (employer_id) REFERENCES public.employers(user_id) NOT VALID;




ALTER TABLE ONLY public.cv_images
    ADD CONSTRAINT fk45mkhvcre9qc8y099tmcrxot3 FOREIGN KEY (jobHunter_user_id) REFERENCES public.jobHunters(user_id);




ALTER TABLE ONLY public.job_adverts
    ADD CONSTRAINT position_fk_id FOREIGN KEY (position_id) REFERENCES public.positions(id) NOT VALID;




ALTER TABLE ONLY public.cv_schools
    ADD CONSTRAINT jobHunter_id_fk FOREIGN KEY (jobHunter_id) REFERENCES public.jobHunters(user_id) NOT VALID;




ALTER TABLE ONLY public.cv_programming_language
    ADD CONSTRAINT jobHunter_id_fk FOREIGN KEY (jobHunter_id) REFERENCES public.jobHunters(user_id) NOT VALID;




ALTER TABLE ONLY public.cv_links
    ADD CONSTRAINT jobHunter_id_fk FOREIGN KEY (jobHunter_id) REFERENCES public.jobHunters(user_id) NOT VALID;




ALTER TABLE ONLY public.cv_images
    ADD CONSTRAINT jobHunter_id_fk FOREIGN KEY (jobHunter_id) REFERENCES public.jobHunters(user_id) NOT VALID;




ALTER TABLE ONLY public.cv_foreign_languages
    ADD CONSTRAINT jobHunter_id_fk FOREIGN KEY (jobHunter_id) REFERENCES public.jobHunters(user_id) NOT VALID;




ALTER TABLE ONLY public.cv_experiences
    ADD CONSTRAINT jobHunter_id_fk FOREIGN KEY (jobHunter_id) REFERENCES public.jobHunters(user_id) NOT VALID;




ALTER TABLE ONLY public.cv_cover_letters
    ADD CONSTRAINT jobHunter_id_fk FOREIGN KEY (jobHunter_id) REFERENCES public.jobHunters(user_id) NOT VALID;




ALTER TABLE ONLY public.employers
    ADD CONSTRAINT user_id FOREIGN KEY (user_id) REFERENCES public.users(id) NOT VALID;




ALTER TABLE ONLY public.jobHunters
    ADD CONSTRAINT user_id FOREIGN KEY (user_id) REFERENCES public.users(id) NOT VALID;




ALTER TABLE ONLY public.staffers
    ADD CONSTRAINT user_id FOREIGN KEY (user_id) REFERENCES public.users(id) NOT VALID;




ALTER TABLE ONLY public.authentication_codes
    ADD CONSTRAINT user_id FOREIGN KEY (user_id) REFERENCES public.users(id) NOT VALID;



